import { Property, Credential, NavItem } from "@/types";

// ==================== NAVIGATION DATA ====================

export const navItems: NavItem[] = [
  { label: "Accueil", href: "/" },
  { label: "Nos Biens", href: "/biens" },
  { label: "Réalisations", href: "/realisations" },
  { label: "Qui Sommes-Nous", href: "/about" },
];

// ==================== CREDENTIALS DATA ====================

export const credentials: Credential[] = [
  { value: "10", label: "Années d'expérience", suffix: "+" },
  { value: "50", label: "Opérations réalisées", suffix: "+" },
  { value: "24", label: "Offre d'achat", suffix: "h" },
  { value: "100", label: "Fonds propres", suffix: "%" },
];

// ==================== PROPERTIES DATA ====================

export const properties: Property[] = [
  // ========== DISPONIBLES ==========
  {
    id: "1",
    title: "Jean Médecin – 4P",
    slug: "jean-medecin-4p",
    reference: "22393",
    location: {
      city: "Nice",
      neighborhood: "Jean Médecin",
      address: "33 rue de Paris",
      postalCode: "06000",
      coordinates: { lat: 43.7030, lng: 7.2620 },
    },
    price: 550000,
    surface: 62,
    rooms: 4,
    bedrooms: 3,
    bathrooms: 2,
    availability: "disponible",
    isRealisation: true,
    type: "appartement",
    images: {
      main: "/images/properties/jean-medecin-4p.jpeg",
      gallery: [],
    },
    description: "Magnifique appartement 4 pièces situé en étage élevé avec ascenseur, entièrement rénové avec des prestations haut de gamme. L'appartement se compose d'un vaste séjour lumineux, d'une cuisine moderne entièrement équipée, de trois grandes chambres confortables, ainsi que de deux salles d'eau contemporaines. Opportunité parfaite pour de la colocation haut de gamme ou de la location saisonnière à forte rentabilité.",
    features: ["Étage élevé", "Ascenseur", "Proche tramway", "Idéal investissement", "Rénovation haut de gamme"],
    isFeatured: true,
    createdAt: "2024-01-05",
    updatedAt: "2024-01-05",
  },
  {
    id: "2",
    title: "Gioffredo – 4P – Nice",
    slug: "gioffredo-4p-nice",
    reference: "22388",
    location: {
      city: "Nice",
      neighborhood: "Centre",
      address: "33 rue Gioffredo",
      postalCode: "06000",
      coordinates: { lat: 43.6980, lng: 7.2650 },
    },
    price: 845000,
    surface: 80,
    rooms: 4,
    bedrooms: 3,
    bathrooms: 2,
    availability: "disponible",
    isRealisation: true,
    type: "appartement",
    images: {
      main: "/images/properties/gioffredo-4p.jpg",
      gallery: [],
    },
    description: "Superbe appartement traversant situé au 3e étage avec ascenseur d'un immeuble de caractère. Bénéficiant d'une double orientation Nord/Sud, il offre une luminosité parfaite tout au long de la journée et deux balcons idéalement disposés de chaque côté. Actuellement en rénovation premium avec matériaux nobles, optimisation des volumes, confort moderne et finitions soignées.",
    features: ["Traversant Nord/Sud", "Balcons deux côtés", "Ascenseur", "Rénovation premium", "Proche tramway"],
    isFeatured: true,
    createdAt: "2024-01-08",
    updatedAt: "2024-01-08",
  },
  {
    id: "3",
    title: "Pastorelli « Durandy » – 4P",
    slug: "pastorelli-durandy-4p",
    reference: "22385",
    location: {
      city: "Nice",
      neighborhood: "Centre",
      address: "13 ter rue Pastorelli",
      postalCode: "06000",
      coordinates: { lat: 43.7010, lng: 7.2700 },
    },
    price: 895000,
    surface: 85,
    rooms: 4,
    bedrooms: 3,
    bathrooms: 2,
    availability: "disponible",
    isRealisation: true,
    type: "appartement",
    images: {
      main: "/images/properties/pastorelli-durandi-4p.jpg",
      gallery: [],
    },
    description: "Superbe appartement traversant situé au 4e étage d'un immeuble de standing avec ascenseur, en plein cœur de Nice. En cours de rénovation premium, il sera vendu entièrement meublé, offrant une solution clé en main. L'appartement se compose d'un vaste séjour lumineux ouvrant sur balcon, d'une cuisine design entièrement équipée, de trois chambres confortables, ainsi que de deux salles d'eau modernes.",
    features: ["Traversant", "Balcons deux côtés", "Ascenseur", "Meublé", "Rénovation haut de gamme", "Clé en main"],
    isFeatured: true,
    createdAt: "2024-01-10",
    updatedAt: "2024-01-10",
  },
  {
    id: "4",
    title: "« Donatello » Carré d'Or – 3P",
    slug: "donatello-carre-dor-3p",
    reference: "22371",
    location: {
      city: "Nice",
      neighborhood: "Carré d'Or",
      address: "30 rue Hôtel des Postes",
      postalCode: "06000",
      coordinates: { lat: 43.6960, lng: 7.2650 },
    },
    price: 639000,
    surface: 65,
    rooms: 3,
    bedrooms: 2,
    bathrooms: 2,
    availability: "disponible",
    isRealisation: false,
    type: "appartement",
    images: {
      main: "/images/properties/donatello-carre-or.jpg",
      gallery: [
        "/images/properties/donatello-carre-or-2.jpg",
        "/images/properties/donatello-carre-or-3.jpg",
        "/images/properties/donatello-carre-or-4.jpg",
        "/images/properties/donatello-carre-or-5.jpg",
        "/images/properties/donatello-carre-or-6.jpg",
        "/images/properties/donatello-carre-or-7.jpg",
        "/images/properties/donatello-carre-or-8.jpg",
        "/images/properties/donatello-carre-or-9.jpeg",
      ],
    },
    description: "Situé au 8ème (avant-dernier) étage avec ascenseur d'un immeuble de grand standing, en plein Carré d'Or de Nice, cet appartement de 3 pièces traversant offre un cadre de vie rare, mêlant élégance, lumière et emplacement de premier ordre. À rénover, on découvre une vaste pièce de vie baignée de lumière, ouverte sur une vaste terrasse plein sud. Au nord, 2 chambres confortables avec salle de bain et salle de douche. Cave incluse, garage en option.",
    features: ["Avant-dernier étage", "Terrasse plein sud", "Traversant", "Cave", "Garage en option", "À rénover"],
    isFeatured: true,
    createdAt: "2024-01-12",
    updatedAt: "2024-01-12",
  },
  {
    id: "5",
    title: "Nice-Fabron « Ciel de Fabron »",
    slug: "nice-fabron-ciel-de-fabron",
    reference: "22347",
    location: {
      city: "Nice",
      neighborhood: "Fabron",
      address: "25 avenue Joseph Giordan",
      postalCode: "06200",
      coordinates: { lat: 43.6896, lng: 7.2328 },
    },
    price: 349000,
    surface: 52,
    rooms: 2,
    bedrooms: 1,
    bathrooms: 1,
    availability: "disponible",
    isRealisation: true,
    type: "appartement",
    images: {
      main: "/images/properties/nice-fabron-ciel-1.jpg",
      gallery: [
        "/images/properties/nice-fabron-ciel-2.jpg",
        "/images/properties/nice-fabron-ciel-3.jpg",
        "/images/properties/nice-fabron-ciel-4.jpg",
        "/images/properties/nice-fabron-ciel-5.jpg",
        "/images/properties/nice-fabron-ciel-6.jpg",
        "/images/properties/nice-fabron-ciel-7.jpg",
        "/images/properties/nice-fabron-ciel-8.jpg",
        "/images/properties/nice-fabron-ciel-9.jpg",
        "/images/properties/nice-fabron-ciel-10.jpg",
        "/images/properties/nice-fabron-ciel-11.jpg",
        "/images/properties/nice-fabron-ciel-12.jpg",
        "/images/properties/nice-fabron-ciel-13.jpg",
        "/images/properties/nice-fabron-ciel-14.jpg",
        "/images/properties/nice-fabron-ciel-15.jpg",
        "/images/properties/nice-fabron-ciel-16.jpg"
      ],
    },
    description: "Dans l'une des plus belles résidences du secteur, « Le Ciel de Fabron », superbe appartement de 52 m² entièrement rénové et meublé avec des matériaux haut de gamme. Situé au 3e étage sur 4 avec ascenseur, il dispose d'un séjour lumineux ouvrant sur une terrasse de 20 m² exposée plein sud, sans vis-à-vis, avec une vue totalement dégagée. La résidence offre des prestations exceptionnelles: gardien 24h/24, piscine, terrains de tennis, restaurant, espace pétanque.",
    features: ["Terrasse 20m²", "Vue dégagée", "Piscine", "Tennis", "Gardien 24h/24", "Ascenseur", "Meublé"],
    isFeatured: true,
    createdAt: "2024-01-15",
    updatedAt: "2024-01-15",
  },

  // ========== RÉALISATIONS (VENDUES) ==========
  {
    id: "6",
    title: "Nice Massena – Hôtel de Ville",
    slug: "nice-massena-hotel-de-ville",
    reference: "22366",
    location: {
      city: "Nice",
      neighborhood: "Massena",
      address: "Proche Hôtel de Ville",
      postalCode: "06000",
      coordinates: { lat: 43.6970, lng: 7.2710 },
    },
    price: 660000,
    surface: 122,
    rooms: 5,
    bedrooms: 4,
    bathrooms: 1,
    availability: "disponible",
    isRealisation: true,
    type: "appartement",
    images: {
      main: "/images/properties/nice-massena-hotel-de-ville.jpg",
      gallery: [
        "/images/properties/nice-massena-hotel-de-ville-2.jpg"
      ],
    },
    description: "Situé dans une rue prisée à deux pas de l'Hôtel de Ville, ce vaste appartement de 122 m² au 4e étage d'un immeuble dont les parties communes ont été entièrement rénovées offre un potentiel rare. 5 pièces à réagencer selon vos envies, grand balcon donnant sur rue. Usage mixte autorisé : idéal résidence principale, libéral ou investissement locatif type Airbnb. Appartement à rénover entièrement.",
    features: ["122m²", "5 pièces", "Balcon", "Usage mixte", "Airbnb autorisé", "À rénover"],
    isFeatured: false,
    createdAt: "2024-01-01",
    updatedAt: "2024-01-01",
  },
  {
    id: "7",
    title: "Nice Coulée verte – « Le Grand Hôtel »",
    slug: "nice-coulee-verte-grand-hotel",
    reference: "22088",
    location: {
      city: "Nice",
      neighborhood: "Coulée Verte",
      address: "Rue Gioffredo",
      postalCode: "06000",
      coordinates: { lat: 43.7012, lng: 7.2701 },
    },
    price: 635000,
    surface: 53,
    rooms: 2,
    bedrooms: 1,
    bathrooms: 1,
    availability: "vendu",
    isRealisation: true,
    type: "appartement",
    images: {
      main: "/images/properties/nice-coulee-verte-grand-hotel.jpg",
      gallery: [
        "/images/properties/nice-coulee-verte-grand-hotel2.jpg",
        "/images/properties/nice-coulee-verte-grand-hotel3.jpg",
        "/images/properties/nice-coulee-verte-grand-hotel4.jpg",
        "/images/properties/nice-coulee-verte-grand-hotel5.jpg",
        "/images/properties/nice-coulee-verte-grand-hotel6.jpg",
        "/images/properties/nice-coulee-verte-grand-hotel7.jpg",
        "/images/properties/nice-coulee-verte-grand-hotel8.jpg",
        "/images/properties/nice-coulee-verte-grand-hotel9.jpg",
        "/images/properties/nice-coulee-verte-grand-hotel10.jpg",
        "/images/properties/nice-coulee-verte-grand-hotel11.jpg",
        "/images/properties/nice-coulee-verte-grand-hotel12.jpg",
        "/images/properties/nice-coulee-verte-grand-hotel13.jpg",
        "/images/properties/nice-coulee-verte-grand-hotel14.jpg",
        "/images/properties/nice-coulee-verte-grand-hotel15.jpg",
        "/images/properties/nice-coulee-verte-grand-hotel16.jpg",
        "/images/properties/nice-coulee-verte-grand-hotel17.jpg",
        "/images/properties/nice-coulee-verte-grand-hotel18.jpg",
        "/images/properties/nice-coulee-verte-grand-hotel19.jpg",
        "/images/properties/nice-coulee-verte-grand-hotel20.jpg",
        "/images/properties/nice-coulee-verte-grand-hotel21.jpg",
        "/images/properties/nice-coulee-verte-grand-hotel22.jpg",
        "/images/properties/nice-coulee-verte-grand-hotel23.jpg",
        "/images/properties/nice-coulee-verte-grand-hotel24.jpg",
        "/images/properties/nice-coulee-verte-grand-hotel25.jpg",
        "/images/properties/nice-coulee-verte-grand-hotel26.jpg",
        "/images/properties/nice-coulee-verte-grand-hotel27.jpg",
        "/images/properties/nice-coulee-verte-grand-hotel28.jpg",
        "/images/properties/nice-coulee-verte-grand-hotel29.jpg",
        "/images/properties/nice-coulee-verte-grand-hotel30.jpg",
        "/images/properties/nice-coulee-verte-grand-hotel31.jpg",
        "/images/properties/nice-coulee-verte-grand-hotel32.jpg"
      ],
    },
    description: "Superbe appartement de 53m² accompagné d'une terrasse de 10m², situé au deuxième étage d'une des résidences les plus prisées de Nice, « Le Grand Hôtel ». Cette résidence prestigieuse dispose d'un gardien, d'élégantes parties communes ainsi qu'un magnifique jardin parfaitement entretenu. Situé à seulement une minute à pied de la célèbre Place Massena. Entièrement meublé avec des prestations très haut de gamme.",
    features: ["Terrasse 10m²", "Résidence prestige", "Gardien", "Jardin", "Ascenseur", "Cave", "Proche Place Massena"],
    isFeatured: true,
    createdAt: "2023-07-20",
    updatedAt: "2024-01-05",
  },
  {
    id: "8",
    title: "Nice Vieille Ville – Droite",
    slug: "nice-vieille-ville-droite",
    reference: "21802",
    location: {
      city: "Nice",
      neighborhood: "Vieux Nice",
      address: "10 rue Droite",
      postalCode: "06000",
      coordinates: { lat: 43.6958, lng: 7.2756 },
    },
    price: 260000,
    surface: 0,
    rooms: 2,
    bedrooms: 1,
    bathrooms: 1,
    availability: "vendu",
    isRealisation: true,
    type: "appartement",
    images: {
      main: "/images/properties/nice-vieille-ville-droite.jpg",
      gallery: [
        "/images/properties/nice-vieille-ville-droite2.jpg",
        "/images/properties/nice-vieille-ville-droite3.jpg",
        "/images/properties/nice-vieille-ville-droite4.jpg",
        "/images/properties/nice-vieille-ville-droite5.jpg",
        "/images/properties/nice-vieille-ville-droite6.jpg",
        "/images/properties/nice-vieille-ville-droite7.jpg",
        "/images/properties/nice-vieille-ville-droite8.jpg",
        "/images/properties/nice-vieille-ville-droite9.jpg",
        "/images/properties/nice-vieille-ville-droite10.jpg",
        "/images/properties/nice-vieille-ville-droite11.jpg"
      ],
    },
    description: "Sublime 2 pièces entièrement rénové par architecte d'intérieur. Meublé à neuf, rénovation haut de gamme, cuisine sur mesure équipée luxe, superbe salle d'eau avec grande douche à l'italienne, dressing sur mesure, parquet chevron chêne massif. Situé au 10 rue Droite à 5 minutes de la mer, en plein cœur du quartier Vieux Nice.",
    features: ["Architecte d'intérieur", "Parquet chêne massif", "Cuisine sur mesure", "Douche italienne", "Meublé", "Proche mer"],
    isFeatured: true,
    createdAt: "2023-06-15",
    updatedAt: "2023-12-01",
  },
  {
    id: "9",
    title: "Nice Vieille Ville – Pairolière (1)",
    slug: "nice-vieille-ville-pairoliere-1",
    reference: "21797",
    location: {
      city: "Nice",
      neighborhood: "Vieux Nice",
      address: "Rue Pairolière",
      postalCode: "06000",
      coordinates: { lat: 43.6962, lng: 7.2745 },
    },
    price: 209000,
    surface: 0,
    rooms: 1,
    bedrooms: 1,
    bathrooms: 1,
    availability: "vendu",
    isRealisation: true,
    type: "appartement",
    images: {
      main: "/images/properties/nice-peroliere-1-1.png",
      gallery: [
        "/images/properties/nice-peroliere-1-2.jpg",
        "/images/properties/nice-peroliere-1-3.jpg",
        "/images/properties/nice-peroliere-1-4.jpg",
        "/images/properties/nice-peroliere-1-5.png",
        "/images/properties/nice-peroliere-1-6.png",
        "/images/properties/nice-peroliere-1-7.png",
        "/images/properties/nice-peroliere-1-8.png",
        "/images/properties/nice-peroliere-1-9.png"
      ],
    },
    description: "Somptueux studio type 2P situé dans la vieille ville de Nice complètement réhabilité, à quelques mètres de la Place Garibaldi. 4ème étage avec ascenseur.",
    features: ["Vieux Nice", "Proche Place Garibaldi", "Ascenseur", "Réhabilité"],
    isFeatured: false,
    createdAt: "2023-05-10",
    updatedAt: "2023-10-01",
  },
  {
    id: "10",
    title: "Nice Vieille Ville – Pairolière (2)",
    slug: "nice-vieille-ville-pairoliere-2",
    reference: "21795",
    location: {
      city: "Nice",
      neighborhood: "Vieux Nice",
      address: "Rue Pairolière",
      postalCode: "06000",
      coordinates: { lat: 43.6962, lng: 7.2745 },
    },
    price: 225000,
    surface: 0,
    rooms: 1,
    bedrooms: 1,
    bathrooms: 1,
    availability: "vendu",
    isRealisation: true,
    type: "appartement",
    images: {
      main: "/images/properties/nice-peroliere-2-1.png",
      gallery: [
        "/images/properties/nice-peroliere-2-2.jpg",
        "/images/properties/nice-peroliere-2-3.png",
        "/images/properties/nice-peroliere-2-4.png",
        "/images/properties/nice-peroliere-2-5.png",
        "/images/properties/nice-peroliere-2-6.png",
        "/images/properties/nice-peroliere-2-7.png",
        "/images/properties/nice-peroliere-2-8.png"
      ],
    },
    description: "Somptueux studio type 2P situé dans la vieille ville de Nice complètement réhabilité, à quelques mètres de la Place Garibaldi et des plages. 4ème étage avec ascenseur.",
    features: ["Vieux Nice", "Proche Place Garibaldi", "Proche plages", "Ascenseur", "Réhabilité"],
    isFeatured: true,
    createdAt: "2023-05-15",
    updatedAt: "2023-10-05",
  },
  {
    id: "11",
    title: "Nice Hypercentre – Gioffredo",
    slug: "nice-hypercentre-gioffredo",
    reference: "21793",
    location: {
      city: "Nice",
      neighborhood: "Hypercentre",
      address: "Rue Gioffredo",
      postalCode: "06000",
      coordinates: { lat: 43.6985, lng: 7.2660 },
    },
    price: 322000,
    surface: 49,
    rooms: 2,
    bedrooms: 1,
    bathrooms: 1,
    availability: "vendu",
    isRealisation: true,
    type: "appartement",
    images: {
      main: "/images/properties/hypercentre-gioffredo.jpg",
      gallery: [
        "/images/properties/hypercentre-gioffredo2.jpg",
        "/images/properties/hypercentre-gioffredo3.jpg",
        "/images/properties/hypercentre-gioffredo4.jpg"
      ],
    },
    description: "2P de 49 m², situé rue Gioffredo, au 2ème étage avec ascenseur donnant sur cour intérieure au calme absolu dans un immeuble ancien avec beaucoup de cachet. Restructuration totale.",
    features: ["Calme absolu", "Cour intérieure", "Ascenseur", "Immeuble de caractère", "Restructuration totale"],
    isFeatured: false,
    createdAt: "2023-04-20",
    updatedAt: "2023-09-15",
  },
  {
    id: "12",
    title: "Nice Hypercentre – Dubouchage",
    slug: "nice-hypercentre-dubouchage",
    reference: "21791",
    location: {
      city: "Nice",
      neighborhood: "Hypercentre",
      address: "Secteur Dubouchage",
      postalCode: "06000",
      coordinates: { lat: 43.7000, lng: 7.2680 },
    },
    price: 349000,
    surface: 41,
    rooms: 2,
    bedrooms: 1,
    bathrooms: 1,
    availability: "vendu",
    isRealisation: true,
    type: "appartement",
    images: {
      main: "/images/properties/hypercentre-dubouchage.jpg",
      gallery: [
        "/images/properties/hypercentre-dubouchage2.jpg",
        "/images/properties/hypercentre-dubouchage3.jpg",
        "/images/properties/hypercentre-dubouchage4.jpg"
      ],
    },
    description: "Somptueux 2P de 41 m², dans l'hypercentre de Nice, secteur Dubouchage. 3ème étage avec ascenseur. Balcon et parking collectif.",
    features: ["Hypercentre", "Ascenseur", "Balcon", "Parking collectif"],
    isFeatured: false,
    createdAt: "2023-04-10",
    updatedAt: "2023-09-01",
  },
  {
    id: "13",
    title: "Nice Fleurs – Saint Philippe (1)",
    slug: "nice-fleurs-saint-philippe-1",
    reference: "21788",
    location: {
      city: "Nice",
      neighborhood: "Les Fleurs",
      address: "Rue Saint Philippe",
      postalCode: "06000",
      coordinates: { lat: 43.7089, lng: 7.2489 },
    },
    price: 269000,
    surface: 36,
    rooms: 2,
    bedrooms: 1,
    bathrooms: 1,
    availability: "vendu",
    isRealisation: true,
    type: "appartement",
    images: {
      main: "/images/properties/nice-fleur-1-1.jpg",
      gallery: [
        "/images/properties/nice-fleur-1-2.jpg",
        "/images/properties/nice-fleur-1-3.webp"
      ],
    },
    description: "2P de 36 m² carrez secteur Fleurs en étage dans immeuble de standing. Mer à 1 minute à pied.",
    features: ["Immeuble standing", "Proche mer", "36m² Carrez"],
    isFeatured: false,
    createdAt: "2023-03-20",
    updatedAt: "2023-08-15",
  },
  {
    id: "14",
    title: "Nice Fleurs – Saint Philippe (2)",
    slug: "nice-fleurs-saint-philippe-2",
    reference: "21786",
    location: {
      city: "Nice",
      neighborhood: "Les Fleurs",
      address: "Rue Saint Philippe",
      postalCode: "06000",
      coordinates: { lat: 43.7089, lng: 7.2489 },
    },
    price: 249000,
    surface: 36,
    rooms: 2,
    bedrooms: 1,
    bathrooms: 1,
    availability: "vendu",
    isRealisation: true,
    type: "appartement",
    images: {
      main: "/images/properties/nice-fleur-2-1.jpg",
      gallery: [
        "/images/properties/nice-fleur-2-2.jpg",
        "/images/properties/nice-fleur-2-3.jpg",
        "/images/properties/nice-fleur-2-4.jpg"
      ],
    },
    description: "Somptueux 2P de 36m² carrez, au deuxième étage avec une jolie vue échappée mer situé rue Saint Philippe. Vendu meublé.",
    features: ["Vue mer", "Meublé", "36m² Carrez"],
    isFeatured: true,
    createdAt: "2022-09-05",
    updatedAt: "2023-08-15",
  },
  {
    id: "15",
    title: "Menton Carré d'Or – Massena",
    slug: "menton-carre-dor-massena",
    reference: "21779",
    location: {
      city: "Menton",
      neighborhood: "Carré d'Or",
      address: "Centre Menton",
      postalCode: "06500",
      coordinates: { lat: 43.7747, lng: 7.4997 },
    },
    price: 239000,
    surface: 0,
    rooms: 2,
    bedrooms: 1,
    bathrooms: 1,
    availability: "vendu",
    isRealisation: true,
    type: "appartement",
    images: {
      main: "/images/properties/menton-carre-or.webp",
      gallery: [
        "/images/properties/menton-carre-or2.webp",
        "/images/properties/menton-carre-or3.webp"
      ],
    },
    description: "Joli 2P avec terrasse situé dans le cœur de Menton. 4ème étage avec ascenseur dans immeuble de standing.",
    features: ["Terrasse", "Ascenseur", "Immeuble standing", "Centre Menton"],
    isFeatured: false,
    createdAt: "2023-02-15",
    updatedAt: "2023-07-01",
  },
  {
    id: "16",
    title: "Nice Vieille ville – Bunico",
    slug: "nice-vieille-ville-bunico",
    reference: "21777",
    location: {
      city: "Nice",
      neighborhood: "Vieux Nice",
      address: "Rue Bunico",
      postalCode: "06000",
      coordinates: { lat: 43.6955, lng: 7.2750 },
    },
    price: 295000,
    surface: 58,
    rooms: 3,
    bedrooms: 2,
    bathrooms: 1,
    availability: "vendu",
    isRealisation: true,
    type: "appartement",
    images: {
      main: "/images/properties/nice-bunico.jpg",
      gallery: [
        "/images/properties/nice-bunico2.jpg",
        "/images/properties/nice-bunico3.jpg",
        "/images/properties/nice-bunico4.jpg"
      ],
    },
    description: "Dans immeuble niçois bien tenu, à proximité des commerces et des plages, 3 pièces de 58 m² au 3ème étage sans ascenseur. Traversant, il comprend une entrée, un séjour, une cuisine indépendante, deux chambres. L'opportunité de rénover à vos goûts. Parfaite localisation pour un pied-à-terre.",
    features: ["Traversant", "58m²", "Proche plages", "À rénover", "Idéal pied-à-terre"],
    isFeatured: false,
    createdAt: "2023-02-10",
    updatedAt: "2023-06-20",
  },
  {
    id: "17",
    title: "Nice Coulée verte – Jean Jaurès",
    slug: "nice-coulee-verte-jean-jaures",
    reference: "21775",
    location: {
      city: "Nice",
      neighborhood: "Coulée Verte",
      address: "Boulevard Jean Jaurès",
      postalCode: "06000",
      coordinates: { lat: 43.7034, lng: 7.2663 },
    },
    price: 549000,
    surface: 87,
    rooms: 4,
    bedrooms: 2,
    bathrooms: 1,
    availability: "vendu",
    isRealisation: true,
    type: "appartement",
    images: {
      main: "/images/properties/nice-coulee-verte-jean-jaures.png",
      gallery: [
        "/images/properties/nice-coulee-verte-jean-jaures2.png",
        "/images/properties/nice-coulee-verte-jean-jaures3.png",
        "/images/properties/nice-coulee-verte-jean-jaures4.png"
      ],
    },
    description: "Coulée verte, Boulevard Jean Jaurès, appartement de type quatre pièces au troisième étage d'un immeuble en bon état. 87m² habitables. Séjour exposition plein ouest avec balcon avec vue panoramique sur la coulée verte et les collines, composé d'une entrée, d'un séjour avec possibilité d'ouverture sur une chambre, deux chambres dont une avec grenier/mezzanine, une cuisine indépendante.",
    features: ["Vue panoramique", "Balcon", "Mezzanine", "Exposition Ouest", "87m²"],
    isFeatured: true,
    createdAt: "2023-09-20",
    updatedAt: "2024-01-10",
  },
  {
    id: "18",
    title: "Nice Vieille Ville – Droite (2)",
    slug: "nice-vieille-ville-droite-2",
    reference: "21773",
    location: {
      city: "Nice",
      neighborhood: "Vieux Nice",
      address: "Rue Droite",
      postalCode: "06000",
      coordinates: { lat: 43.6958, lng: 7.2756 },
    },
    price: 291000,
    surface: 0,
    rooms: 2,
    bedrooms: 1,
    bathrooms: 1,
    availability: "vendu",
    isRealisation: true,
    type: "appartement",
    images: {
      main: "/images/properties/nice-vieille-ville-droite-2-1.jpg",
      gallery: [
        "/images/properties/nice-vieille-ville-droite-2-2.jpg",
        "/images/properties/nice-vieille-ville-droite-2-3.jpg",
        "/images/properties/nice-vieille-ville-droite-2-4.jpg",
        "/images/properties/nice-vieille-ville-droite-2-5.jpg",
        "/images/properties/nice-vieille-ville-droite-2-6.jpg",
        "/images/properties/nice-vieille-ville-droite-2-7.jpg",
        "/images/properties/nice-vieille-ville-droite-2-8.jpg"
      ],
    },
    description: "Somptueux appartement type 2P situé dans un des quartiers les plus recherchés de la ville de Nice, le vieux Nice. L'appartement situé rue droite, à quelques minutes à pied des plages, de la place Garibaldi et des restaurants, se trouve au troisième étage sans ascenseur au sein d'une copropriété rénovée pleine de charme. Entièrement restauré et repensé par un cabinet d'architecte d'intérieur.",
    features: ["Vieux Nice", "Proche plages", "Architecte d'intérieur", "Copropriété rénovée"],
    isFeatured: true,
    createdAt: "2023-06-15",
    updatedAt: "2023-12-01",
  },
  {
    id: "19",
    title: "Nice Centre – Carabacel",
    slug: "nice-centre-carabacel",
    reference: "21770",
    location: {
      city: "Nice",
      neighborhood: "Carabacel",
      address: "Secteur Carabacel",
      postalCode: "06000",
      coordinates: { lat: 43.7050, lng: 7.2750 },
    },
    price: 299000,
    surface: 64,
    rooms: 2,
    bedrooms: 1,
    bathrooms: 1,
    availability: "vendu",
    isRealisation: true,
    type: "appartement",
    images: {
      main: "/images/properties/nice-centre-carabacel.jpg",
      gallery: [
        "/images/properties/nice-centre-carabacel2.jpg",
        "/images/properties/nice-centre-carabacel3.jpg",
        "/images/properties/nice-centre-carabacel4.jpg",
        "/images/properties/nice-centre-carabacel5.jpg",
        "/images/properties/nice-centre-carabacel6.jpg"
      ],
    },
    description: "Nice bas Cimiez. Proche de l'ensemble des commodités et du cœur de ville, dans immeuble de style Art déco ravalé en 2020, vaste 2 pièces de 64m² bien distribué et facilement transformable en 3 pièces. Belle pièce de vie offrant une vue sur les palais bourgeois environnants. Ce bien au fort potentiel conviendra à tous types de projets.",
    features: ["Art Déco", "64m²", "Transformable en 3P", "Vue dégagée", "À rénover"],
    isFeatured: false,
    createdAt: "2023-01-15",
    updatedAt: "2023-06-01",
  },
  {
    id: "20",
    title: "Nice Coulée Verte – Gallieni (1)",
    slug: "nice-coulee-verte-gallieni-1",
    reference: "21768",
    location: {
      city: "Nice",
      neighborhood: "Coulée Verte",
      address: "Avenue Gallieni",
      postalCode: "06000",
      coordinates: { lat: 43.7025, lng: 7.2680 },
    },
    price: 279000,
    surface: 40,
    rooms: 2,
    bedrooms: 1,
    bathrooms: 1,
    availability: "vendu",
    isRealisation: true,
    type: "appartement",
    images: {
      main: "/images/properties/nice-gallieni-1-1.jpg",
      gallery: [
        "/images/properties/nice-gallieni-1-2.jpg",
        "/images/properties/nice-gallieni-1-3.jpg",
        "/images/properties/nice-gallieni-1-4.jpg"
      ],
    },
    description: "2P d'environ 40 m² situé Avenue Gallieni, au deuxième étage dans un immeuble niçois. L'appartement donne sur la future coulée verte.",
    features: ["Vue Coulée Verte", "40m²", "Immeuble niçois"],
    isFeatured: false,
    createdAt: "2023-01-10",
    updatedAt: "2023-05-20",
  },
  {
    id: "21",
    title: "Nice Coulée Verte – Gallieni (2)",
    slug: "nice-coulee-verte-gallieni-2",
    reference: "21765",
    location: {
      city: "Nice",
      neighborhood: "Coulée Verte",
      address: "Avenue Gallieni",
      postalCode: "06000",
      coordinates: { lat: 43.7025, lng: 7.2680 },
    },
    price: 269000,
    surface: 40,
    rooms: 2,
    bedrooms: 1,
    bathrooms: 1,
    availability: "vendu",
    isRealisation: true,
    type: "appartement",
    images: {
      main: "/images/properties/nice-gallieni-2-1.jpg",
      gallery: [
        "/images/properties/nice-gallieni-2-2.jpg",
        "/images/properties/nice-gallieni-2-3.jpg",
        "/images/properties/nice-gallieni-2-4.jpg",
        "/images/properties/nice-gallieni-2-5.jpg"
      ],
    },
    description: "2P d'environ 40 m² situé Avenue Gallieni, au premier étage, avec une vue sur la future coulée verte.",
    features: ["Vue Coulée Verte", "40m²", "Premier étage"],
    isFeatured: false,
    createdAt: "2023-01-05",
    updatedAt: "2023-05-15",
  },
  {
    id: "22",
    title: "Nice Carré d'Or – Buffa",
    slug: "nice-carre-or-buffa",
    reference: "19387",
    location: {
      city: "Nice",
      neighborhood: "Carré d'Or",
      address: "Secteur Buffa",
      postalCode: "06000",
      coordinates: { lat: 43.6947, lng: 7.2597 },
    },
    price: 399000,
    surface: 40,
    rooms: 2,
    bedrooms: 1,
    bathrooms: 1,
    availability: "vendu",
    isRealisation: true,
    type: "appartement",
    images: {
      main: "/images/properties/nice-buffa.jpg",
      gallery: [
        "/images/properties/nice-buffa2.jpg",
        "/images/properties/nice-buffa4.jpg",
        "/images/properties/nice-buffa5.jpg",
        "/images/properties/nice-buffa6.jpg",
        "/images/properties/nice-buffa7.jpg",
        "/images/properties/nice-buffa8.jpg",
        "/images/properties/nice-buffa9.jpg",
        "/images/properties/nice-buffa10.jpg"
      ],
    },
    description: "L'appartement, situé à deux pas des plages, de la zone piétonne et des restaurants, se trouve au troisième étage avec ascenseur. Cet appartement 2 pièces de 40m² exposé Sud a été entièrement restauré et repensé par un cabinet d'architecte d'intérieur. Entrée avec rangements, Séjour avec cuisine Américaine entièrement équipée, Une chambre avec rangements sur mesure, Salle de douche, Toilettes séparés, Balconnet.",
    features: ["Proche plages", "Ascenseur", "Exposition Sud", "Architecte d'intérieur", "Cuisine équipée", "Balconnet"],
    isFeatured: true,
    createdAt: "2022-06-15",
    updatedAt: "2023-12-01",
  },
];

// ==================== CITIES DATA ====================

export const cities = [
  { name: "Nice", coordinates: { lat: 43.7102, lng: 7.262 } },
  { name: "Cannes", coordinates: { lat: 43.5528, lng: 7.0174 } },
  { name: "Antibes", coordinates: { lat: 43.5808, lng: 7.1239 } },
  { name: "Monaco", coordinates: { lat: 43.7384, lng: 7.4246 } },
  { name: "Menton", coordinates: { lat: 43.7747, lng: 7.4997 } },
  { name: "Saint-Jean-Cap-Ferrat", coordinates: { lat: 43.6833, lng: 7.3333 } },
  { name: "Villefranche-sur-Mer", coordinates: { lat: 43.7042, lng: 7.3117 } },
];

// ==================== HELPER FUNCTIONS ====================

export function getPropertyById(id: string): Property | undefined {
  return properties.find((p) => p.id === id);
}

export function getPropertyBySlug(slug: string): Property | undefined {
  return properties.find((p) => p.slug === slug);
}

export function getAvailableProperties(): Property[] {
  return properties.filter((p) => p.availability === "disponible");
}

export function getRealisations(): Property[] {
  return properties.filter((p) => p.isRealisation);
}

export function getSoldRealisations(): Property[] {
  return properties.filter((p) => p.isRealisation && p.availability === "vendu");
}

export function getFeaturedProperties(): Property[] {
  return properties.filter((p) => p.isFeatured);
}

export function getFeaturedAvailable(): Property[] {
  return properties.filter((p) => p.isFeatured && p.availability === "disponible");
}

export function getFeaturedRealisations(): Property[] {
  return properties.filter((p) => p.isFeatured && p.isRealisation);
}